#!/bin/bash

# HOME="/home/rcs/opt/java/harborview"

JS="src/main/webapp/js/maunaloa"

JSC="$JS/canvas"
SVG="$JS/svg"

# FILES="/js/charts.js /js/canvas/rulers.js /js/canvas/linechart.js /js/canvas/levelline.js /js/canvas/scrapbook.js"

JS_FILES="$JS/charts.js $JSC/linechart.js $JSC/rulers.js"

JS_MODULES="$JSC/chart.js $SVG/draggable.js"

UGLIFY="node/node_modules/uglify-es/bin/uglifyjs"

$UGLIFY $JS_FILES -o $JS/maunaloa.min.js --compress --ecma 6 -b

$UGLIFY $JS_MODULES -o $JS/modules.min.js --compress --ecma 6 -b

exit 0
