#!/bin/bash

TARGET=/harborview/src/main/webapp/css/harborview.css

# sass --style compressed sass-src/harborview.scss src/resources/public/css/harborview.css

docker run --rm -v /home/rcs/opt/java/harborview:/harborview rcs/sass  sass /harborview/sass-src/harborview.scss $TARGET

# sass --watch sass-src/harborview.scss:src/resources/public/css/harborview.css

exit 0
