#!/bin/bash


usage()
{
cat << EOF
usage: $0 options

OPTIONS:
   -h      Show this message
   -o      --optimize flag
   -i      Module index (1: Charts, 2: Options, 3: OptionPurchase, 4: Critters)
EOF
}

EV="1"
MODULE=
OPTIMIZE="0"
TMP="/home/rcs/opt/elmcommon"
while getopts “hoi:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         o)
             OTPIMIZE="1"
             ;;
         i)
             MODULE=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

DOCKER_IMG="rcs/elm:0.19"

case $MODULE in

    1) ELM="src/Maunaloa/Charts/Main.elm"
       JS="elm-charts.js"
       TODIR="maunaloa"
        ;;

    2) ELM="src/Maunaloa/Options/Main.elm"
       JS="elm-options.js"
       TODIR="maunaloa"
        ;;

    3) ELM="src/Maunaloa/OptionPurchases.elm"
       JS="elm-optionpurchases.js"
       TODIR="maunaloa"
        ;;

    4) ELM="src/Critters/Main.elm"
       JS="elm-critters.js"
       TODIR="critters"
        ;;

    5) ELM="src/Vinapu/Projects.elm"
       JS="elm-projects.js"
       TODIR="vinapu"
        ;;
esac

if [ "$OPTIMIZE" = "1" ]; then
    docker run --user $(id -u):$(id -g) -it --rm -v "$(pwd):/code" -v "$TMP:/tmp" -w "/code" -e "HOME=/tmp" $DOCKER_IMG make $ELM --output $JS --optimize
    # docker run --user $(id -u):$(id -g) -it --rm -v "$(pwd):/code" -v "/tmp:/tmp" -w "/code" -e "HOME=/tmp" -u $UID:$GID $DOCKER_IMG make $ELM --output $JS --optimize
else
    docker run --user $(id -u):$(id -g) -it --rm -v "$(pwd):/code" -v "$TMP:/tmp" -w "/code" -e "HOME=/tmp" $DOCKER_IMG make $ELM --output $JS
    # docker run --user $(id -u):$(id -g) -it --rm -v "$(pwd):/code" -v "/tmp:/tmp" -w "/code" -e "HOME=/tmp" -u $UID:$GID $DOCKER_IMG make $ELM --output $JS
fi

cp $JS ../src/main/resources/static/js/$TODIR/$JS

cp $JS ../out/production/resources/static/js/$TODIR/$JS

exit 0

# #!/bin/sh
#
# set -e
#
# js="elm.js"
# min="elm.min.js"
#
# elm make --optimize --output=$js $@
#
# uglifyjs $js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output=$min
#
# echo "Initial size: $(cat $js | wc -c) bytes  ($js)"
# echo "Minified size:$(cat $min | wc -c) bytes  ($min)"
# echo "Gzipped size: $(cat $min | gzip -c | wc -c) bytes"
